# Generated by Django 6.0.6 on 2026-07-03 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=300, verbose_name='Xabar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('declined', 'Rad etilgan')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Familyasi')),
                ('gender', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=5, verbose_name='Jinsi')),
                ('birth_year', models.CharField(blank=True, max_length=20, verbose_name="Tug'ilgan yili")),
                ('death_year', models.CharField(blank=True, max_length=20, verbose_name='Vafot etgan yili')),
                ('occupation', models.CharField(blank=True, max_length=150, verbose_name='Kasbi')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Yashash joyi')),
                ('bio', models.TextField(blank=True, verbose_name="Qisqacha ma'lumot")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/', verbose_name='Surati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_people', to=settings.AUTH_USER_MODEL)),
                ('child_family', models.ForeignKey(blank=True, help_text="Bu odam farzand bo'lgan oila", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shajara.family')),
            ],
            options={
                'verbose_name': 'Shaxs',
                'verbose_name_plural': 'Shaxslar',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_father', to='shajara.person'),
        ),
        migrations.AddField(
            model_name='family',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families_as_mother', to='shajara.person'),
        ),
        migrations.CreateModel(
            name='UserPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linked_user', to='shajara.person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
