# Generated by Django 6.0.6 on 2026-07-03 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shajara', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.CharField(blank=True, max_length=20, verbose_name="Tug'ilgan yili (taxminiy)"),
        ),
        migrations.CreateModel(
            name='PersonStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Hikoya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories_written', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='shajara.person')),
            ],
            options={
                'verbose_name': 'Hikoya',
                'verbose_name_plural': 'Hikoyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
