# Generated by Django 6.0.6 on 2026-07-05 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_userperson_to_tree(apps, schema_editor):
    """Backfill Tree rows from the old one-tree-per-user UserPerson links,
    and point existing ConnectionRequest rows at the sender's new Tree."""
    UserPerson = apps.get_model('shajara', 'UserPerson')
    Tree = apps.get_model('shajara', 'Tree')
    ConnectionRequest = apps.get_model('shajara', 'ConnectionRequest')

    user_to_tree = {}
    for up in UserPerson.objects.select_related('user').all():
        tree = Tree.objects.create(
            owner_id=up.user_id, root_person_id=up.person_id,
            name=f"{up.user.username}ning shajarasi", visibility='private',
        )
        user_to_tree[up.user_id] = tree

    for req in ConnectionRequest.objects.all():
        tree = user_to_tree.get(req.from_user_id)
        if tree:
            req.from_tree_id = tree.id
            req.save(update_fields=['from_tree'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shajara', '0002_person_birth_date_alter_person_birth_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('visibility', models.CharField(choices=[('private', 'Shaxsiy'), ('public', 'Ommaviy')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to=settings.AUTH_USER_MODEL)),
                ('root_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_tree_root', to='shajara.person')),
            ],
            options={
                'verbose_name': 'Shajara',
                'verbose_name_plural': 'Shajaralar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='from_tree',
            field=models.ForeignKey(blank=True, help_text="Qaysi shajarangiz orqali bog'lanmoqchisiz", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='shajara.tree'),
        ),
        migrations.CreateModel(
            name='TreeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_comments', to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shajara.tree')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeGratitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitudes', to='shajara.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_gratitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tree', 'user')},
            },
        ),
        migrations.RunPython(migrate_userperson_to_tree, noop_reverse),
        migrations.DeleteModel(
            name='UserPerson',
        ),
    ]
