# Generated by Django 6.0.6 on 2026-09-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shajara', '0005_tree_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_district',
            field=models.CharField(blank=True, max_length=100, verbose_name="Tug'ilgan tumani"),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_region',
            field=models.CharField(blank=True, choices=[('', '— tanlanmagan —'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ("Farg'ona viloyati", "Farg'ona viloyati"), ('Jizzax viloyati', 'Jizzax viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ("Qoraqalpog'iston Respublikasi", "Qoraqalpog'iston Respublikasi"), ('Samarqand viloyati', 'Samarqand viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Toshkent shahri', 'Toshkent shahri'), ('Boshqa', "Boshqa (O'zbekistondan tashqari)")], max_length=60, verbose_name="Tug'ilgan viloyati"),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_village',
            field=models.CharField(blank=True, max_length=150, verbose_name="Tug'ilgan qishloq/mahalla"),
        ),
        migrations.AddField(
            model_name='person',
            name='patronymic',
            field=models.CharField(blank=True, help_text="Masalan: Ahmadovich yoki Ahmad o'g'li", max_length=100, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='root_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooted_trees', to='shajara.person'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Tizimga kirdi'), ('login_failed', 'Kirish muvaffaqiyatsiz'), ('logout', 'Tizimdan chiqdi'), ('email_verified', 'Emailni tasdiqladi'), ('password_reset', 'Parolni tikladi'), ('tree_create', 'Shajara yaratdi'), ('tree_import', "Shajarani JSON'dan tikladi"), ('tree_update', "Shajara sozlamalarini o'zgartirdi"), ('tree_delete', "Shajarani o'chirdi"), ('tree_export', 'Shajarani yuklab oldi'), ('person_add', "Shaxs qo'shdi"), ('person_edit', 'Shaxsni tahrirladi'), ('person_delete', "Shaxsni o'chirdi"), ('story_add', 'Hikoya yozdi'), ('comment_add', 'Izoh qoldirdi'), ('gratitude', 'Minnatdorchilik bildirdi'), ('request_send', "Bog'lanish so'rovi yubordi"), ('request_accept', "So'rovni qabul qildi"), ('request_decline', "So'rovni rad etdi"), ('admin_view_private', "Admin: shaxsiy shajarani ko'rdi"), ('admin_user_update', "Admin: foydalanuvchini o'zgartirdi"), ('admin_tree_update', "Admin: shajarani o'zgartirdi"), ('admin_tree_delete', "Admin: shajarani o'chirdi"), ('admin_match_run', 'Admin: moslik qidiruvini ishga tushirdi'), ('admin_match_reject', 'Admin: moslikni rad etdi'), ('admin_merge', 'Admin: shaxslarni birlashtirdi')], db_index=True, max_length=30)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shajara.person')),
                ('tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shajara.tree')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faollik',
                'verbose_name_plural': 'Faollik jurnali',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_key', models.CharField(max_length=40, unique=True)),
                ('score', models.PositiveSmallIntegerField(db_index=True, verbose_name='Ishonch indeksi')),
                ('breakdown', models.JSONField(default=list)),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', "Ko'rib chiqilmagan"), ('merged', 'Birlashtirilgan'), ('rejected', 'Rad etilgan')], db_index=True, default='pending', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shajara.person')),
                ('person_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shajara.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moslik nomzodi',
                'verbose_name_plural': 'Moslik nomzodlari',
                'ordering': ['-score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('persons_scanned', models.PositiveIntegerField(default=0)),
                ('pairs_compared', models.PositiveIntegerField(default=0)),
                ('candidates_found', models.PositiveIntegerField(default=0)),
                ('candidates_new', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MergeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kept_name', models.CharField(max_length=250)),
                ('dropped_name', models.CharField(max_length=250)),
                ('persons_merged', models.PositiveIntegerField(default=1)),
                ('log', models.JSONField(default=list)),
                ('trees', models.JSONField(default=list)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merges', to='shajara.matchcandidate')),
                ('kept_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shajara.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
