# Generated by Django 6.0.6 on 2026-09-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shajara', '0006_admin_panel_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('', '— tanlanmagan —'), ('Andijon viloyati', 'Andijon viloyati'), ('Buxoro viloyati', 'Buxoro viloyati'), ("Farg'ona viloyati", "Farg'ona viloyati"), ('Jizzax viloyati', 'Jizzax viloyati'), ('Xorazm viloyati', 'Xorazm viloyati'), ('Namangan viloyati', 'Namangan viloyati'), ('Navoiy viloyati', 'Navoiy viloyati'), ('Qashqadaryo viloyati', 'Qashqadaryo viloyati'), ("Qoraqalpog'iston Respublikasi", "Qoraqalpog'iston Respublikasi"), ('Samarqand viloyati', 'Samarqand viloyati'), ('Sirdaryo viloyati', 'Sirdaryo viloyati'), ('Surxondaryo viloyati', 'Surxondaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Toshkent shahri', 'Toshkent shahri'), ('Boshqa', "Boshqa (O'zbekistondan tashqari)")], max_length=60, verbose_name='Viloyati'),
        ),
    ]
