# Generated by Django 6.0.6 on 2026-09-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shajara', '0007_userprofile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='layout',
            field=models.JSONField(blank=True, default=dict, verbose_name='Xarita tartibi'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Tizimga kirdi'), ('login_failed', 'Kirish muvaffaqiyatsiz'), ('logout', 'Tizimdan chiqdi'), ('email_verified', 'Emailni tasdiqladi'), ('password_reset', 'Parolni tikladi'), ('tree_create', 'Shajara yaratdi'), ('tree_import', "Shajarani JSON'dan tikladi"), ('tree_update', "Shajara sozlamalarini o'zgartirdi"), ('tree_delete', "Shajarani o'chirdi"), ('tree_export', 'Shajarani yuklab oldi'), ('tree_layout', 'Xarita tartibini saqladi'), ('person_add', "Shaxs qo'shdi"), ('person_edit', 'Shaxsni tahrirladi'), ('person_delete', "Shaxsni o'chirdi"), ('story_add', 'Hikoya yozdi'), ('comment_add', 'Izoh qoldirdi'), ('gratitude', 'Minnatdorchilik bildirdi'), ('request_send', "Bog'lanish so'rovi yubordi"), ('request_accept', "So'rovni qabul qildi"), ('request_decline', "So'rovni rad etdi"), ('admin_view_private', "Admin: shaxsiy shajarani ko'rdi"), ('admin_user_update', "Admin: foydalanuvchini o'zgartirdi"), ('admin_tree_update', "Admin: shajarani o'zgartirdi"), ('admin_tree_delete', "Admin: shajarani o'chirdi"), ('admin_match_run', 'Admin: moslik qidiruvini ishga tushirdi'), ('admin_match_reject', 'Admin: moslikni rad etdi'), ('admin_merge', 'Admin: shaxslarni birlashtirdi')], db_index=True, max_length=30),
        ),
    ]
