# Generated by Django 6.0.6 on 2026-09-14 04:09

import django.db.models.deletion
import shajara.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shajara', '0008_tree_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='era',
            field=models.CharField(blank=True, help_text='Masalan: XIV–XVI asrlar', max_length=100, verbose_name='Davr'),
        ),
        migrations.AddField(
            model_name='tree',
            name='kind',
            field=models.CharField(choices=[('oilaviy', 'Oilaviy shajara'), ('talimiy', "Ta'limiy shajara")], db_index=True, default='oilaviy', max_length=10, verbose_name='Turi'),
        ),
        migrations.AddField(
            model_name='tree',
            name='sources',
            field=models.TextField(blank=True, help_text='Darslik, kitob yoki maqolalar — har birini yangi qatordan yozing', verbose_name='Manbalar'),
        ),
        migrations.AddField(
            model_name='tree',
            name='subject',
            field=models.CharField(blank=True, help_text="Masalan: O'zbekiston tarixi — Temuriylar davri", max_length=150, verbose_name='Fan / mavzu'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('oila', 'Oilam shajarasini tuzmoqchiman'), ('abituriyent', 'Abituriyentman'), ('talaba', 'Talabaman'), ('oqituvchi', "O'qituvchiman"), ('ixlosmand', 'Tarix ixlosmandiman')], max_length=12, verbose_name='Kimsiz'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Tizimga kirdi'), ('login_failed', 'Kirish muvaffaqiyatsiz'), ('logout', 'Tizimdan chiqdi'), ('email_verified', 'Emailni tasdiqladi'), ('password_reset', 'Parolni tikladi'), ('tree_create', 'Shajara yaratdi'), ('tree_import', "Shajarani JSON'dan tikladi"), ('tree_update', "Shajara sozlamalarini o'zgartirdi"), ('tree_delete', "Shajarani o'chirdi"), ('tree_export', 'Shajarani yuklab oldi'), ('tree_layout', 'Xarita tartibini saqladi'), ('invite_create', 'Taklif havolasi yaratdi'), ('invite_revoke', 'Taklif havolasini bekor qildi'), ('member_join', "Shajaraga qo'shildi"), ('member_role', "A'zo huquqini o'zgartirdi"), ('member_remove', "A'zoni chiqarib yubordi"), ('member_leave', 'Shajaradan chiqdi'), ('quiz_finish', 'Test ishladi'), ('person_add', "Shaxs qo'shdi"), ('person_edit', 'Shaxsni tahrirladi'), ('person_delete', "Shaxsni o'chirdi"), ('story_add', 'Hikoya yozdi'), ('comment_add', 'Izoh qoldirdi'), ('gratitude', 'Minnatdorchilik bildirdi'), ('request_send', "Bog'lanish so'rovi yubordi"), ('request_accept', "So'rovni qabul qildi"), ('request_decline', "So'rovni rad etdi"), ('admin_view_private', "Admin: shaxsiy shajarani ko'rdi"), ('admin_user_update', "Admin: foydalanuvchini o'zgartirdi"), ('admin_tree_update', "Admin: shajarani o'zgartirdi"), ('admin_tree_delete', "Admin: shajarani o'chirdi"), ('admin_match_run', 'Admin: moslik qidiruvini ishga tushirdi'), ('admin_match_reject', 'Admin: moslikni rad etdi'), ('admin_merge', 'Admin: shaxslarni birlashtirdi')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='shajara.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=shajara.models.make_invite_token, editable=False, max_length=40, unique=True)),
                ('role', models.CharField(choices=[('muharrir', 'Muharrir'), ('kuzatuvchi', 'Kuzatuvchi')], default='muharrir', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('revoked', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='shajara.tree')),
            ],
            options={
                'verbose_name': 'Taklif havolasi',
                'verbose_name_plural': 'Taklif havolalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('muharrir', 'Muharrir'), ('kuzatuvchi', 'Kuzatuvchi')], default='muharrir', max_length=12, verbose_name='Huquqi')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='shajara.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Shajara a'zosi",
                'verbose_name_plural': "Shajara a'zolari",
                'ordering': ['joined_at'],
                'unique_together': {('tree', 'user')},
            },
        ),
    ]
