# Generated by Django 6.0.6 on 2026-09-14 08:00

import django.db.models.deletion
import shajara.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shajara', '0009_learning_and_sharing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=shajara.models.preview_upload_to, verbose_name="Ko'rinish rasmi"),
        ),
        migrations.AddField(
            model_name='tree',
            name='preview_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=shajara.models.make_export_code, editable=False, max_length=10, unique=True)),
                ('tree_name', models.CharField(max_length=150)),
                ('tree_kind', models.CharField(choices=[('oilaviy', 'Oilaviy shajara'), ('talimiy', "Ta'limiy shajara")], default='oilaviy', max_length=10)),
                ('root_name', models.CharField(blank=True, max_length=210)),
                ('kind', models.CharField(choices=[('pdf', 'PDF kitob'), ('png', 'PNG rasm'), ('svg', 'SVG rasm')], max_length=5)),
                ('people_count', models.PositiveIntegerField(default=0)),
                ('generations', models.PositiveIntegerField(default=0)),
                ('contributors', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='shajara.tree')),
            ],
            options={
                'verbose_name': 'Eksport yozuvi',
                'verbose_name_plural': 'Eksport yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
