# Generated by Django 6.0.6 on 2026-09-14 10:36

import django.db.models.deletion
import shajara.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shajara', '0010_exports_and_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Tizimga kirdi'), ('login_failed', 'Kirish muvaffaqiyatsiz'), ('logout', 'Tizimdan chiqdi'), ('email_verified', 'Emailni tasdiqladi'), ('password_reset', 'Parolni tikladi'), ('tree_create', 'Shajara yaratdi'), ('tree_import', "Shajarani JSON'dan tikladi"), ('tree_update', "Shajara sozlamalarini o'zgartirdi"), ('tree_delete', "Shajarani o'chirdi"), ('tree_export', 'Shajarani yuklab oldi'), ('tree_layout', 'Xarita tartibini saqladi'), ('invite_create', 'Taklif havolasi yaratdi'), ('invite_revoke', 'Taklif havolasini bekor qildi'), ('member_join', "Shajaraga qo'shildi"), ('member_role', "A'zo huquqini o'zgartirdi"), ('member_remove', "A'zoni chiqarib yubordi"), ('member_leave', 'Shajaradan chiqdi'), ('quiz_finish', 'Test ishladi'), ('map_create', 'Tarixiy xarita yaratdi'), ('map_update', "Tarixiy xaritani o'zgartirdi"), ('map_delete', "Tarixiy xaritani o'chirdi"), ('person_add', "Shaxs qo'shdi"), ('person_edit', 'Shaxsni tahrirladi'), ('person_delete', "Shaxsni o'chirdi"), ('story_add', 'Hikoya yozdi'), ('comment_add', 'Izoh qoldirdi'), ('gratitude', 'Minnatdorchilik bildirdi'), ('request_send', "Bog'lanish so'rovi yubordi"), ('request_accept', "So'rovni qabul qildi"), ('request_decline', "So'rovni rad etdi"), ('admin_view_private', "Admin: shaxsiy shajarani ko'rdi"), ('admin_user_update', "Admin: foydalanuvchini o'zgartirdi"), ('admin_tree_update', "Admin: shajarani o'zgartirdi"), ('admin_tree_delete', "Admin: shajarani o'chirdi"), ('admin_match_run', 'Admin: moslik qidiruvini ishga tushirdi'), ('admin_match_reject', 'Admin: moslikni rad etdi'), ('admin_merge', 'Admin: shaxslarni birlashtirdi')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='HistoricalMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=shajara.models.make_tree_key, editable=False, max_length=22, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('era', models.CharField(blank=True, max_length=100, verbose_name='Davr')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('sources', models.TextField(blank=True, verbose_name='Manbalar')),
                ('image', models.ImageField(upload_to=shajara.models.map_upload_to, verbose_name='Xarita rasmi')),
                ('image_width', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('private', 'Shaxsiy'), ('public', 'Ommaviy')], default='private', max_length=10)),
                ('is_sample', models.BooleanField(default=False, verbose_name='Namunaviy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_maps', to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_maps', to='shajara.tree', verbose_name="Bog'langan shajara")),
            ],
            options={
                'verbose_name': 'Tarixiy xarita',
                'verbose_name_plural': 'Tarixiy xaritalar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MapPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nomi')),
                ('kind', models.CharField(choices=[('shahar', 'Shahar'), ('poytaxt', 'Poytaxt'), ('jang', 'Jang'), ('voqea', 'Voqea'), ('qarorgoh', 'Qarorgoh'), ('tugilgan', "Tug'ilgan joy"), ('vafot', 'Vafot etgan joy'), ('yodgorlik', 'Yodgorlik')], default='shahar', max_length=12, verbose_name='Turi')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('year', models.IntegerField(blank=True, help_text='Miloddan avvalgi yillar manfiy: -329', null=True, verbose_name='Yil')),
                ('year_end', models.IntegerField(blank=True, null=True, verbose_name='Tugagan yil')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='shajara.historicalmap')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_places', to='shajara.person')),
            ],
            options={
                'ordering': ['year', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MapRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('kind', models.CharField(choices=[('harbiy', 'Harbiy yurish'), ('savdo', "Savdo yo'li"), ('kochish', "Ko'chish"), ('sayohat', 'Sayohat'), ('elchilik', 'Elchilik')], default='harbiy', max_length=12, verbose_name='Turi')),
                ('color', models.CharField(default='#b3261e', max_length=7, verbose_name='Rangi')),
                ('year_start', models.IntegerField(blank=True, null=True)),
                ('year_end', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('stops', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='shajara.historicalmap')),
            ],
            options={
                'ordering': ['year_start', 'id'],
            },
        ),
    ]
