# Generated by Django 6.0.6 on 2026-09-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shajara', '0012_profile_presence_and_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='featured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name="Ochiq sahifada ko'rsatilsin"),
        ),
        migrations.AddField(
            model_name='tree',
            name='public_views',
            field=models.PositiveIntegerField(default=0, verbose_name="Ochiq sahifa ko'rishlari"),
        ),
        migrations.AddField(
            model_name='tree',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Google natijasida sarlavha ostida chiqadigan 1–2 gap (70–160 belgi)', max_length=300, verbose_name='Qidiruv tizimlari uchun tavsif'),
        ),
        migrations.AddField(
            model_name='tree',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True, verbose_name='Ochiq sahifa manzili'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Tizimga kirdi'), ('login_failed', 'Kirish muvaffaqiyatsiz'), ('logout', 'Tizimdan chiqdi'), ('email_verified', 'Emailni tasdiqladi'), ('password_reset', 'Parolni tikladi'), ('tree_create', 'Shajara yaratdi'), ('tree_import', "Shajarani JSON'dan tikladi"), ('tree_update', "Shajara sozlamalarini o'zgartirdi"), ('tree_delete', "Shajarani o'chirdi"), ('tree_export', 'Shajarani yuklab oldi'), ('tree_layout', 'Xarita tartibini saqladi'), ('invite_create', 'Taklif havolasi yaratdi'), ('invite_revoke', 'Taklif havolasini bekor qildi'), ('member_join', "Shajaraga qo'shildi"), ('member_role', "A'zo huquqini o'zgartirdi"), ('member_remove', "A'zoni chiqarib yubordi"), ('member_leave', 'Shajaradan chiqdi'), ('quiz_finish', 'Test ishladi'), ('map_create', 'Tarixiy xarita yaratdi'), ('map_update', "Tarixiy xaritani o'zgartirdi"), ('map_delete', "Tarixiy xaritani o'chirdi"), ('person_add', "Shaxs qo'shdi"), ('person_edit', 'Shaxsni tahrirladi'), ('person_delete', "Shaxsni o'chirdi"), ('story_add', 'Hikoya yozdi'), ('comment_add', 'Izoh qoldirdi'), ('gratitude', 'Minnatdorchilik bildirdi'), ('request_send', "Bog'lanish so'rovi yubordi"), ('request_accept', "So'rovni qabul qildi"), ('request_decline', "So'rovni rad etdi"), ('admin_view_private', "Admin: shaxsiy shajarani ko'rdi"), ('admin_user_update', "Admin: foydalanuvchini o'zgartirdi"), ('admin_tree_update', "Admin: shajarani o'zgartirdi"), ('admin_tree_delete', "Admin: shajarani o'chirdi"), ('admin_match_run', 'Admin: moslik qidiruvini ishga tushirdi'), ('admin_match_reject', 'Admin: moslikni rad etdi'), ('admin_merge', 'Admin: shaxslarni birlashtirdi'), ('admin_seo_update', "Admin: ochiq (SEO) sahifani o'zgartirdi")], db_index=True, max_length=30),
        ),
    ]
