# Generated by Django 6.0.6 on 2026-09-24 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shajara', '0013_open_pages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('landing', 'Bosh sahifa (/)'), ('open_index', "Tarixiy shajaralar ro'yxati (/shajaralar/)")], max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Sarlavha (title)')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Tavsif (description)')),
                ('og_image', models.CharField(blank=True, max_length=300, verbose_name='Ulashish rasmi')),
                ('noindex', models.BooleanField(default=False, verbose_name='Qidiruvdan yashirish (noindex)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Sahifa SEO'si",
                'verbose_name_plural': "Sahifalar SEO'si",
            },
        ),
        migrations.CreateModel(
            name='SeoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=120, unique=True, verbose_name="Fayl yo'li")),
                ('content', models.TextField(blank=True, verbose_name='Mazmuni')),
                ('content_type', models.CharField(choices=[('text/plain', 'Matn (.txt)'), ('text/html', 'HTML (Google/Yandex tasdiqlash)'), ('application/xml', 'XML (Bing BingSiteAuth.xml)'), ('application/json', 'JSON')], default='text/plain', max_length=30, verbose_name='Turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yoqilgan')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO fayli',
                'verbose_name_plural': 'SEO fayllari',
                'ordering': ['path'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('login', 'Tizimga kirdi'), ('login_failed', 'Kirish muvaffaqiyatsiz'), ('logout', 'Tizimdan chiqdi'), ('email_verified', 'Emailni tasdiqladi'), ('password_reset', 'Parolni tikladi'), ('tree_create', 'Shajara yaratdi'), ('tree_import', "Shajarani JSON'dan tikladi"), ('tree_update', "Shajara sozlamalarini o'zgartirdi"), ('tree_delete', "Shajarani o'chirdi"), ('tree_export', 'Shajarani yuklab oldi'), ('tree_layout', 'Xarita tartibini saqladi'), ('invite_create', 'Taklif havolasi yaratdi'), ('invite_revoke', 'Taklif havolasini bekor qildi'), ('member_join', "Shajaraga qo'shildi"), ('member_role', "A'zo huquqini o'zgartirdi"), ('member_remove', "A'zoni chiqarib yubordi"), ('member_leave', 'Shajaradan chiqdi'), ('quiz_finish', 'Test ishladi'), ('map_create', 'Tarixiy xarita yaratdi'), ('map_update', "Tarixiy xaritani o'zgartirdi"), ('map_delete', "Tarixiy xaritani o'chirdi"), ('person_add', "Shaxs qo'shdi"), ('person_edit', 'Shaxsni tahrirladi'), ('person_delete', "Shaxsni o'chirdi"), ('story_add', 'Hikoya yozdi'), ('comment_add', 'Izoh qoldirdi'), ('gratitude', 'Minnatdorchilik bildirdi'), ('request_send', "Bog'lanish so'rovi yubordi"), ('request_accept', "So'rovni qabul qildi"), ('request_decline', "So'rovni rad etdi"), ('admin_view_private', "Admin: shaxsiy shajarani ko'rdi"), ('admin_user_update', "Admin: foydalanuvchini o'zgartirdi"), ('admin_tree_update', "Admin: shajarani o'zgartirdi"), ('admin_tree_delete', "Admin: shajarani o'chirdi"), ('admin_match_run', 'Admin: moslik qidiruvini ishga tushirdi'), ('admin_match_reject', 'Admin: moslikni rad etdi'), ('admin_merge', 'Admin: shaxslarni birlashtirdi'), ('admin_seo_update', "Admin: ochiq (SEO) sahifani o'zgartirdi"), ('admin_seo_settings', "Admin: sayt SEO sozlamalarini o'zgartirdi"), ('admin_seo_file', "Admin: SEO faylini o'zgartirdi"), ('admin_email_test', 'Admin: test xat yubordi'), ('email_failed', 'Email yuborilmadi')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='e-Shajara', max_length=80, verbose_name='Sayt nomi')),
                ('default_description', models.CharField(blank=True, help_text="Sahifada o'z tavsifi bo'lmasa shu chiqadi. 70–160 belgi tavsiya etiladi.", max_length=300, verbose_name='Standart tavsif (meta description)')),
                ('default_og_image', models.CharField(blank=True, help_text="To'liq havola (https://...) yoki /static/img/... yo'li. 1200×630 tavsiya etiladi.", max_length=300, verbose_name='Standart ulashish rasmi (og:image)')),
                ('google_verification', models.CharField(blank=True, max_length=200, verbose_name='Google Search Console kodi')),
                ('bing_verification', models.CharField(blank=True, max_length=200, verbose_name='Bing Webmaster kodi')),
                ('yandex_verification', models.CharField(blank=True, max_length=200, verbose_name='Yandex Webmaster kodi')),
                ('ga_measurement_id', models.CharField(blank=True, max_length=30, verbose_name='Google Analytics (G-XXXXXXX)')),
                ('yandex_metrica_id', models.CharField(blank=True, max_length=20, verbose_name='Yandex Metrica raqami')),
                ('extra_head_html', models.TextField(blank=True, help_text="Faqat <meta>, <link> va <script> teglari. Ochiq sahifalarning <head> qismiga qo'yiladi.", verbose_name="Qo'shimcha <head> teglar")),
                ('block_indexing', models.BooleanField(default=False, help_text="Sinov serveri uchun. Yoqilsa robots.txt hammasini taqiqlaydi va sahifalarga noindex qo'shiladi.", verbose_name='Butun saytni qidiruvdan yopish')),
                ('robots_txt', models.TextField(blank=True, help_text="Bo'sh qoldirsangiz avtomatik robots.txt ishlatiladi.", verbose_name="robots.txt (qo'lda)")),
                ('sitemap_extra', models.TextField(blank=True, help_text="Har bir manzilni yangi qatordan yozing (masalan: /haqida/ yoki to'liq https://...).", verbose_name="Sitemap'ga qo'shimcha manzillar")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sayt SEO sozlamasi',
                'verbose_name_plural': 'Sayt SEO sozlamalari',
            },
        ),
    ]
